const data = {
    hsk1: [
        {"hanzi":"爱","pinyin":"ài","english":"love"},
        {"hanzi":"八","pinyin":"bā","english":"eight"},
        {"hanzi":"爸爸","pinyin":"bàba","english":"father"},
        {"hanzi":"杯子","pinyin":"bēizi","english":"cup"},
        {"hanzi":"北京","pinyin":"Běijīng","english":"Beijing"},
        {"hanzi":"本","pinyin":"běn","english":"measure word for books"},
        {"hanzi":"不","pinyin":"bù","english":"not"},
        {"hanzi":"不客气","pinyin":"bú kèqi","english":"you're welcome"},
        {"hanzi":"菜","pinyin":"cài","english":"dish / vegetable"},
        {"hanzi":"茶","pinyin":"chá","english":"tea"},
        {"hanzi":"吃","pinyin":"chī","english":"eat"},
        {"hanzi":"出租车","pinyin":"chūzūchē","english":"taxi"},
        {"hanzi":"打电话","pinyin":"dǎ diànhuà","english":"make a phone call"},
        {"hanzi":"大","pinyin":"dà","english":"big"},
        {"hanzi":"的","pinyin":"de","english":"possessive particle"},
        {"hanzi":"点","pinyin":"diǎn","english":"o'clock / point"},
        {"hanzi":"电脑","pinyin":"diànnǎo","english":"computer"},
        {"hanzi":"电视","pinyin":"diànshì","english":"television"},
        {"hanzi":"电影","pinyin":"diànyǐng","english":"movie"},
        {"hanzi":"东西","pinyin":"dōngxi","english":"thing"},
        {"hanzi":"都","pinyin":"dōu","english":"all"},
        {"hanzi":"读","pinyin":"dú","english":"read"},
        {"hanzi":"对不起","pinyin":"duìbuqǐ","english":"sorry"},
        {"hanzi":"多","pinyin":"duō","english":"many / much"},
        {"hanzi":"多少","pinyin":"duōshao","english":"how much / how many"},
        {"hanzi":"儿子","pinyin":"érzi","english":"son"},
        {"hanzi":"二","pinyin":"èr","english":"two"},
        {"hanzi":"饭店","pinyin":"fàndiàn","english":"restaurant / hotel"},
        {"hanzi":"飞机","pinyin":"fēijī","english":"airplane"},
        {"hanzi":"分钟","pinyin":"fēnzhōng","english":"minute"},
        {"hanzi":"高兴","pinyin":"gāoxìng","english":"happy"},
        {"hanzi":"个","pinyin":"gè","english":"general measure word"},
        {"hanzi":"工作","pinyin":"gōngzuò","english":"work"},
        {"hanzi":"狗","pinyin":"gǒu","english":"dog"},
        {"hanzi":"汉语","pinyin":"Hànyǔ","english":"Chinese language"},
        {"hanzi":"好","pinyin":"hǎo","english":"good"},
        {"hanzi":"号","pinyin":"hào","english":"number / day (of month)"},
        {"hanzi":"喝","pinyin":"hē","english":"drink"},
        {"hanzi":"和","pinyin":"hé","english":"and"},
        {"hanzi":"很","pinyin":"hěn","english":"very"},
        {"hanzi":"后面","pinyin":"hòumiàn","english":"behind"},
        {"hanzi":"回","pinyin":"huí","english":"return"},
        {"hanzi":"会","pinyin":"huì","english":"can / know how to"},
        {"hanzi":"几","pinyin":"jǐ","english":"how many (small number)"},
        {"hanzi":"家","pinyin":"jiā","english":"home / family"},
        {"hanzi":"叫","pinyin":"jiào","english":"be called"},
        {"hanzi":"今天","pinyin":"jīntiān","english":"today"},
        {"hanzi":"九","pinyin":"jiǔ","english":"nine"},
        {"hanzi":"开","pinyin":"kāi","english":"open / drive"},
        {"hanzi":"看","pinyin":"kàn","english":"look / watch"},
        {"hanzi":"看见","pinyin":"kànjiàn","english":"see"},
        {"hanzi":"块","pinyin":"kuài","english":"piece / yuan (colloquial)"},
        {"hanzi":"来","pinyin":"lái","english":"come"},
        {"hanzi":"老师","pinyin":"lǎoshī","english":"teacher"},
        {"hanzi":"了","pinyin":"le","english":"completed action particle"},
        {"hanzi":"冷","pinyin":"lěng","english":"cold"},
        {"hanzi":"里","pinyin":"lǐ","english":"inside"},
        {"hanzi":"六","pinyin":"liù","english":"six"},
        {"hanzi":"妈妈","pinyin":"māma","english":"mother"},
        {"hanzi":"吗","pinyin":"ma","english":"question particle"},
        {"hanzi":"买","pinyin":"mǎi","english":"buy"},
        {"hanzi":"猫","pinyin":"māo","english":"cat"},
        {"hanzi":"没关系","pinyin":"méi guānxi","english":"it's okay / no problem"},
        {"hanzi":"没有","pinyin":"méiyǒu","english":"do not have"},
        {"hanzi":"米饭","pinyin":"mǐfàn","english":"rice (cooked)"},
        {"hanzi":"明天","pinyin":"míngtiān","english":"tomorrow"},
        {"hanzi":"名字","pinyin":"míngzi","english":"name"},
        {"hanzi":"哪","pinyin":"nǎ","english":"which"},
        {"hanzi":"哪儿","pinyin":"nǎr","english":"where"},
        {"hanzi":"那","pinyin":"nà","english":"that"},
        {"hanzi":"呢","pinyin":"ne","english":"question particle"},
        {"hanzi":"能","pinyin":"néng","english":"can / be able to"},
        {"hanzi":"你","pinyin":"nǐ","english":"you"},
        {"hanzi":"年","pinyin":"nián","english":"year"},
        {"hanzi":"女儿","pinyin":"nǚ'ér","english":"daughter"},
        {"hanzi":"朋友","pinyin":"péngyou","english":"friend"},
        {"hanzi":"漂亮","pinyin":"piàoliang","english":"beautiful"},
        {"hanzi":"苹果","pinyin":"píngguǒ","english":"apple"},
        {"hanzi":"七","pinyin":"qī","english":"seven"},
        {"hanzi":"钱","pinyin":"qián","english":"money"},
        {"hanzi":"前面","pinyin":"qiánmiàn","english":"front"},
        {"hanzi":"请","pinyin":"qǐng","english":"please / invite"},
        {"hanzi":"去","pinyin":"qù","english":"go"},
        {"hanzi":"热","pinyin":"rè","english":"hot"},
        {"hanzi":"人","pinyin":"rén","english":"person"},
        {"hanzi":"认识","pinyin":"rènshi","english":"know (someone)"},
        {"hanzi":"三","pinyin":"sān","english":"three"},
        {"hanzi":"商店","pinyin":"shāngdiàn","english":"shop"},
        {"hanzi":"上","pinyin":"shàng","english":"up / on"},
        {"hanzi":"上午","pinyin":"shàngwǔ","english":"morning"},
        {"hanzi":"少","pinyin":"shǎo","english":"few / little"},
        {"hanzi":"谁","pinyin":"shéi","english":"who"},
        {"hanzi":"什么","pinyin":"shénme","english":"what"},
        {"hanzi":"十","pinyin":"shí","english":"ten"},
        {"hanzi":"时候","pinyin":"shíhou","english":"time (moment)"},
        {"hanzi":"是","pinyin":"shì","english":"to be"},
        {"hanzi":"书","pinyin":"shū","english":"book"},
        {"hanzi":"水","pinyin":"shuǐ","english":"water"},
        {"hanzi":"水果","pinyin":"shuǐguǒ","english":"fruit"},
        {"hanzi":"睡觉","pinyin":"shuìjiào","english":"sleep"},
        {"hanzi":"说","pinyin":"shuō","english":"speak / say"},
        {"hanzi":"四","pinyin":"sì","english":"four"},
        {"hanzi":"岁","pinyin":"suì","english":"years old"},
        {"hanzi":"他","pinyin":"tā","english":"he"},
        {"hanzi":"她","pinyin":"tā","english":"she"},
        {"hanzi":"太","pinyin":"tài","english":"too / very"},
        {"hanzi":"天气","pinyin":"tiānqì","english":"weather"},
        {"hanzi":"听","pinyin":"tīng","english":"listen"},
        {"hanzi":"同学","pinyin":"tóngxué","english":"classmate"},
        {"hanzi":"喂","pinyin":"wèi","english":"hello (on phone)"},
        {"hanzi":"我","pinyin":"wǒ","english":"I / me"},
        {"hanzi":"我们","pinyin":"wǒmen","english":"we"},
        {"hanzi":"五","pinyin":"wǔ","english":"five"},
        {"hanzi":"喜欢","pinyin":"xǐhuan","english":"like"},
        {"hanzi":"下","pinyin":"xià","english":"down"},
        {"hanzi":"下午","pinyin":"xiàwǔ","english":"afternoon"},
        {"hanzi":"下雨","pinyin":"xiàyǔ","english":"rain"},
        {"hanzi":"先生","pinyin":"xiānsheng","english":"Mr. / sir"},
        {"hanzi":"现在","pinyin":"xiànzài","english":"now"},
        {"hanzi":"想","pinyin":"xiǎng","english":"want / think"},
        {"hanzi":"小","pinyin":"xiǎo","english":"small"},
        {"hanzi":"小姐","pinyin":"xiǎojiě","english":"Miss"},
        {"hanzi":"些","pinyin":"xiē","english":"some"},
        {"hanzi":"写","pinyin":"xiě","english":"write"},
        {"hanzi":"谢谢","pinyin":"xièxie","english":"thank you"},
        {"hanzi":"星期","pinyin":"xīngqī","english":"week"},
        {"hanzi":"学生","pinyin":"xuésheng","english":"student"},
        {"hanzi":"学习","pinyin":"xuéxí","english":"study"},
        {"hanzi":"学校","pinyin":"xuéxiào","english":"school"},
        {"hanzi":"一","pinyin":"yī","english":"one"},
        {"hanzi":"一点儿","pinyin":"yìdiǎnr","english":"a little"},
        {"hanzi":"衣服","pinyin":"yīfu","english":"clothes"},
        {"hanzi":"医生","pinyin":"yīshēng","english":"doctor"},
        {"hanzi":"医院","pinyin":"yīyuàn","english":"hospital"},
        {"hanzi":"椅子","pinyin":"yǐzi","english":"chair"},
        {"hanzi":"有","pinyin":"yǒu","english":"have"},
        {"hanzi":"月","pinyin":"yuè","english":"month"},
        {"hanzi":"在","pinyin":"zài","english":"at / in"},
        {"hanzi":"再见","pinyin":"zàijiàn","english":"goodbye"},
        {"hanzi":"怎么","pinyin":"zěnme","english":"how"},
        {"hanzi":"怎么样","pinyin":"zěnmeyàng","english":"how about / how is"},
        {"hanzi":"这","pinyin":"zhè","english":"this"},
        {"hanzi":"中国","pinyin":"Zhōngguó","english":"China"},
        {"hanzi":"中午","pinyin":"zhōngwǔ","english":"noon"},
        {"hanzi":"住","pinyin":"zhù","english":"live / stay"},
        {"hanzi":"桌子","pinyin":"zhuōzi","english":"table"},
        {"hanzi":"字","pinyin":"zì","english":"character / word"},
        {"hanzi":"昨天","pinyin":"zuótiān","english":"yesterday"},
        {"hanzi":"做","pinyin":"zuò","english":"do / make"},
        {"hanzi":"坐","pinyin":"zuò","english":"sit"}
    ]
}

export default data